sudo: required
services:
  - docker
before_install:
  - docker pull yshalsager/lineageos:14.1
before_script:
  - cd $HOME && mkdir twrp && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - cd $HOME/twrp/
  - git config --global color.ui false 
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
  - repo sync
  #- wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz
  #  -O $HOME/twrp.tar.xz
  #- tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/amitkhairnar44/twrp_device_asus_X00PD.git -b test1 device/asus/X00P/
  #- git clone https://github.com/raza231198/bionic_libc_zoneinfo.git bionic/libc/zoneinfo
  #- git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/twrp/:rw,z" yshalsager/lineageos:14.1 bash << EOF
    cd /root/twrp/
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh && lunch omni_X00P-eng && make -j16 recoveryimage
    exit
    EOF
#after_success:
  #- export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  #- cp $HOME/twrp/out/target/product/ftj161a/recovery.img $HOME/twrp/TWRP-$version-ftj161a-$(date +"%Y%m%d").img

#deploy:
  #skip_cleanup: true
  #provider: releases
  #api_key: "$GIT_OAUTH_TOKEN_TB"
  #file_glob: true
  #file: $HOME/twrp/*.img
  #on:
    #tags: false
    #repo: TwrpBuilder/android_device_freetel_ftj161a
    #branch: master
#branches:
  #except:
    #- /^(?i:untagged)-.*$/